openapi: 3.0.0
info:
  title: new-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /foo/createFoo:
    post:
      summary: ''
      operationId: post-foo-createFoo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
        '':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
              examples:
                example-1:
                  value:
                    id: string
                    name: string
                    property:
                      name: string
                      value: string
      description: Create Foo
      parameters:
        - schema:
            type: string
          in: header
          name: TenantId
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foo'
            examples:
              example-1:
                value:
                  id: string
                  name: string
                  property:
                    name: string
                    value: string
    parameters: []
components:
  schemas:
    Foo:
      title: Foo
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        property:
          oneOf:
            - properties:
                name:
                  type: string
                value:
                  type: string
          type: object
      x-examples:
        example-1:
          id: string
          name: string
          property:
            name: string
            value: string
